server:
  port: 8900
  servlet:
    context-path: /message
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  application:
    name: car-message-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.23.75.195:3306/message?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true

# minio 参数配置

minio:
  endpoint: http://119.23.75.195:9000
  bucketName: message

rocketmq:
  name-server: 192.168.10.38:9876
  producer:
    group: orderComplains


mq:
  shopordercomplains:
    consumer:
      group: order_shop_consumer_complain
    tag: order_shop_complains
    topic: orderShopComplainsTopic
  powerordercomplains:
    consumer:
      group: order_power_consumer_complain
    tag: order_power_complains
    topic: orderPowerComplainsTopic
  producerordercomplains:
    consumer:
      group: order_producer_consumer_complain
    tag: order_producer_complains
    topic: orderProducerComplainsTopic

swagger:
  base-package: com.woniu.car.message.web.controller
  contact:
    email: "zyy@111.com"
    host: "http://zyy.com"
    name: "zyy"
  description: "信息服务接口"
  title: "信息服务"
  version: 1.0

seata:
  enabled: true
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true

