server:
  port: 8500
  servlet:
    context-path: /auth
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: car-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.21:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#王鹏
#    url: jdbc:mysql://47.108.133.10/car-auth-server?characterEncoding=UTF-8
#    username: root
#    password: 123456

#郑亚云
    url: jdbc:mysql://119.23.75.195/car-auth-server?characterEncoding=UTF-8
    username: root
    password: root




mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#jwt
config:
  jwt:
    secret: "snail-car-life-car-auth-server"
    expire: 8640000
    subject: "snail-car-life-auth-subject"
    tokenPrefix: "com.snail.car.life"

#swagger2
swagger:
  base-package: com.woniu.car.auth.web.controller
  contact:
    email: "1997wty@gmail.com"
    host: "http://wty.com"
    name: "wty"
  description: "认证服务接口"
  title: "后台认证"
  version: 1.0


#minio配置
minio:
  endpoint: http://119.23.75.195:9000
  bucketName: auth

#seata配置
seata:
  enabled: true
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true
  application-id: ${spring.application.name}

