server:
  port: 8199
  servlet:
    context-path: /marketing

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://119.23.75.195:3306/car-marketing-server?useUnicode=true&useSSL=false&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    #seate配置
    alibaba:
      seata:
        tx-service-group: my_text_seata
  # 设置服务名
  application:
    name: car-marketing-server
  servlet:
    multipart:
      max-file-size: 10MB #指定上载文件允许的最大大小。 默认值为1MB
      max-request-size: 10MB  #指定multipart/form-data请求允许的最大大小。 默认值为10MB。
#配置redis
  redis:
    host: 47.108.133.10 # Redis服务器地址
    port: 6399 # Redis服务器连接端口



# seat 配置
seata:
  enabled: true
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true
  application-id: ${spring.application.name}
# minio 参数配置
minio:
  endpoint: http://119.23.75.195:9000
  bucketName: marketing

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #sql打印日志

swagger:
  base-package: com.woniu.car.marketing.web.controller
  contact:
    email: "1360166328@qq.com"
    host: "http://tsl.com"
    name: "tsl"
  description: "促销服务接口"
  title: "促销服务"
  version: 1.0


