server:
  port: 10010
  servlet:
    context-path: /service

spring:
  application:
    name: car-service-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.23.75.195:3306/car-items-server?characterEncoding=utf-8
    username: root
    password: root
  servlet:
    multipart:
      max-request-size: 30MB  #指定multipart/form-data请求允许的最大大小。 默认值为10MB。
      max-file-size: 30MB #指定上载文件允许的最大大小。 默认值为1MB
#  redis:
#    host: localhost
#    port: 6379



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #sql打印日志

swagger:
  base-package: com.woniu.car.service.web.controller
  contact:
    email: "mizunokaede@163.com"
    host: "http://HZX.com"
    name: "HZX"
  description: "汽车服务接口"
  title: "汽车服务"
  version: 1.0

minio:
  endpoint: http://192.168.10.22:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: service

# seat 配置
seata:
  enabled: true
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true
  application-id: ${spring.application.name}



