server:
  port: 8600
  servlet:
    context-path: /user
spring:
  application:
    name: user-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://119.23.75.195:3306/car-user-server?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root


  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
## seat 配置
#seata:
#  enabled: true
#  tx-service-group: my_test_tx_group
#  enable-auto-data-source-proxy: true
#  application-id: ${spring.application.name}


swagger:
  base-package: com.woniu.car.user.web.controller
  contact:
    email: "s@infor.vip"
    host: "sss.qq "
    name: "s"
  description: "用户服务接口"
  title: "用户服务"
  version: 1.0
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #sql打印日志
jackson:
  serialization:
    FAIL_ON_EMPTY_BEANS: false

