server:
  port: 8366
  servlet:
    context-path: /order
#  multipart:
#    max-request-size: 10MB  #指定multipart/form-data请求允许的最大大小。 默认值为10MB。
#    max-file-size: 10MB #指定上载文件允许的最大大小。 默认值为1MB
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: car-order-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.23.75.195:3306/db_car_order?characterEncoding=UTF-8
#    url: jdbc:mysql://47.108.133.10:3306/db_car_order?characterEncoding=UTF-8
    username: root
    password: root

    # redis
    redis:
      host: localhost
      port: 6379
#rocketmq:
#  name-server: 192.168.148.128:9876
#  producer:
#    group: r

swagger:
  base-package: com.woniu.car.order.web.controller
  contact:
    email: "2284905800@qq.com"
    host: ""
    name: "WP"
  description: "用户服务接口"
  title: "用户服务"
  version: 1.0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #配置mybatis-plus将日志打印到控制台
# seat 配置
seata:
  enabled: true
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true
  application-id: ${spring.application.name}

# minio 参数配置
minio:
  endpoint: http://192.168.10.86:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: station